# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1283d08b82c6ef52204ef03ce1687dda2b0914f57f34d97a38df8d08004931287d3a9e56a06fcb94c53b94be17b37e9cd5eb6bba450cd5ec5ec27d40b73deac

test:
  secret_key_base: 1e00940afba4af47f227a57d49f9eca045d8f3e142df402611d59cc0b7e3ca0ff4ec0ed6140b8661b089a7bf72bb255a02c0ecb77a48686fd53bbd599a1edf13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
